// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gcj_wgs_accu_
NumericVector gcj_wgs_accu_(double lon, double lat);
RcppExport SEXP _chinaCRS_gcj_wgs_accu_(SEXP lonSEXP, SEXP latSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< double >::type lat(latSEXP);
    rcpp_result_gen = Rcpp::wrap(gcj_wgs_accu_(lon, lat));
    return rcpp_result_gen;
END_RCPP
}
// bd_wgs_accu_
NumericVector bd_wgs_accu_(double lon, double lat);
RcppExport SEXP _chinaCRS_bd_wgs_accu_(SEXP lonSEXP, SEXP latSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< double >::type lat(latSEXP);
    rcpp_result_gen = Rcpp::wrap(bd_wgs_accu_(lon, lat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_chinaCRS_gcj_wgs_accu_", (DL_FUNC) &_chinaCRS_gcj_wgs_accu_, 2},
    {"_chinaCRS_bd_wgs_accu_", (DL_FUNC) &_chinaCRS_bd_wgs_accu_, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_chinaCRS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
