# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' More accurately convert gcj02 to WGS84 coordinate system
#' @importFrom Rcpp sourceCpp
#' @useDynLib crsAdjustCN
#'
#' @param lon input longitude with gcj02 as crs
#' @param lat input latitude with gcj02 as crs
#' @return A numeric vector with 2 elements contining X and Y numeric vectors
gcj_wgs_accu_ <- function(lon, lat) {
    .Call('_crsAdjustCN_gcj_wgs_accu_', PACKAGE = 'crsAdjustCN', lon, lat)
}

#' More accurately convert bd09 to WGS84 coordinate system
#' @importFrom Rcpp sourceCpp
#' @useDynLib crsAdjustCN
#'
#' @param lon input longitude with bd09 as crs
#' @param lat input latitude with bd09 as crs
#' @return A numeric vector with 2 elements contining X and Y numeric vectors
bd_wgs_accu_ <- function(lon, lat) {
    .Call('_crsAdjustCN_bd_wgs_accu_', PACKAGE = 'crsAdjustCN', lon, lat)
}

